# Generated by Django 4.2.7 on 2025-09-27 16:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('role', models.CharField(choices=[('ADMIN', 'Sistem Yöneticisi'), ('RECTORATE_SECRETARY', 'Rektörlük Sekreteri'), ('FACULTY_SECRETARY', 'Fakülte Sekreteri'), ('DEPARTMENT_SECRETARY', 'Bölüm Sekreteri'), ('ASSISTANT', 'Asistan')], max_length=50, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text='Örnek: CSE101, MATH201', max_length=50, unique=True, verbose_name='Ders Kodu')),
                ('course_name', models.CharField(max_length=255, verbose_name='Ders Adı')),
                ('credit', models.PositiveIntegerField(default=3, help_text='Dersin kredi değeri', verbose_name='Kredi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['department__name', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Ara Sınav'), ('FINAL', 'Final Sınavı'), ('MAKEUP', 'Bütünleme Sınavı'), ('RESIT', 'Tekrar Sınavı')], max_length=50, verbose_name='Sınav Türü')),
                ('exam_level', models.CharField(choices=[('UNDERGRADUATE', 'Lisans'), ('GRADUATE', 'Yüksek Lisans'), ('DOCTORAL', 'Doktora')], max_length=50, verbose_name='Sınav Seviyesi')),
                ('location', models.CharField(help_text='Örnek: Amfi-1, Lab-205', max_length=255, verbose_name='Sınav Yeri')),
                ('exam_datetime', models.DateTimeField(verbose_name='Sınav Tarihi ve Saati')),
                ('duration_minutes', models.PositiveIntegerField(default=120, verbose_name='Sınav Süresi (Dakika)')),
                ('proctor_needed_count', models.PositiveIntegerField(help_text='Bu sınav için kaç gözetmen gerekli', verbose_name='Gerekli Gözetmen Sayısı')),
                ('student_count', models.PositiveIntegerField(default=0, help_text='Sınava katılacak öğrenci sayısı', verbose_name='Öğrenci Sayısı')),
                ('special_notes', models.TextField(blank=True, help_text='Sınav hakkında özel notlar veya talimatlar', null=True, verbose_name='Özel Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.course', verbose_name='Ders')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Sınav',
                'verbose_name_plural': 'Sınavlar',
                'ordering': ['-exam_datetime'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Okul Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Okul',
                'verbose_name_plural': 'Okullar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Fakülte Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='core.school', verbose_name='Okul')),
            ],
            options={
                'verbose_name': 'Fakülte',
                'verbose_name_plural': 'Fakülteler',
                'ordering': ['school__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bölüm Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.faculty', verbose_name='Fakülte')),
            ],
            options={
                'verbose_name': 'Bölüm',
                'verbose_name_plural': 'Bölümler',
                'ordering': ['faculty__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department', verbose_name='Bölüm'),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('start_datetime', models.DateTimeField(verbose_name='Başlangıç Tarihi ve Saati')),
                ('end_datetime', models.DateTimeField(verbose_name='Bitiş Tarihi ve Saati')),
                ('event_type', models.CharField(choices=[('LECTURE', 'Ders'), ('LAB', 'Laboratuvar'), ('MEETING', 'Toplantı'), ('OFFICE_HOURS', 'Ofis Saatleri'), ('PERSONAL', 'Kişisel'), ('EXAM_DUTY', 'Sınav Görevi')], max_length=50, verbose_name='Etkinlik Türü')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yer')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Tekrar Eden Etkinlik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(limit_choices_to={'role': 'ASSISTANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Asistan')),
            ],
            options={
                'verbose_name': 'Takvim Etkinliği',
                'verbose_name_plural': 'Takvim Etkinlikleri',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ProctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('ACCEPTED', 'Kabul Edildi'), ('REJECTED', 'Reddedildi'), ('EXCUSED', 'Mazeretli')], default='PENDING', max_length=50, verbose_name='Durum')),
                ('reason_for_rejection', models.TextField(blank=True, help_text='Görev reddedilirse veya mazeret bildirilirse açıklama', null=True, verbose_name='Red/Mazeret Nedeni')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atama Tarihi')),
                ('response_at', models.DateTimeField(blank=True, help_text='Asistanın yanıt verdiği tarih', null=True, verbose_name='Yanıt Tarihi')),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role__in': ['RECTORATE_SECRETARY', 'FACULTY_SECRETARY', 'DEPARTMENT_SECRETARY']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Atamayı Yapan')),
                ('assistant', models.ForeignKey(limit_choices_to={'role': 'ASSISTANT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Asistan')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Gözetmen Ataması',
                'verbose_name_plural': 'Gözetmen Atamaları',
                'ordering': ['-assigned_at'],
                'unique_together': {('assistant', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='AssistantProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('exam_load_score', models.IntegerField(default=0, help_text='Asistanın aldığı görevlerin toplam puanı', verbose_name='Sınav Yükü Puanı')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to='core.department', verbose_name='Bölüm')),
            ],
            options={
                'verbose_name': 'Asistan Profili',
                'verbose_name_plural': 'Asistan Profilleri',
            },
        ),
    ]
