# Generated by Django 4.2.7 on 2025-09-27 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Kullanıcının bağlı olduğu bölüm (bölüm sekreterleri ve asistanlar için)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='Bölüm'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Kullanıcının bağlı olduğu fakülte (sekreterler ve asistanlar için)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculty', verbose_name='Fakülte'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Sistem Yöneticisi'), ('SECRETARY_RECTORATE', 'Rektörlük Sekreteri'), ('SECRETARY_FACULTY', 'Fakülte Sekreteri'), ('SECRETARY_DEPARTMENT', 'Bölüm Sekreteri'), ('ASSISTANT', 'Asistan')], max_length=50, verbose_name='Rol'),
        ),
    ]
